version: '2.0'

services:
    perfect:
        container_name: "perfect"
        image: "valentinbercot/docker-perfect"
        env_file: ".env"
        volumes:
            - "${PERFECT_SOURCE_PATH}:${PERFECT_TARGET_PATH}"
        ports:
            - "8181:8181"
        entrypoint: "${PERFECT_TARGET_PATH}/docker-entrypoint.sh"
        links:
            - "database"

    database:
        container_name: "${DB_IMAGE}"
        image: "${DB_IMAGE}"
        env_file: ".env"
        volumes:
            - "${DB_SOURCE_PATH}:${DB_TARGET_PATH}"
        ports:
            - "3306:3306"
